apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: opt-karp-on-demand-cons
spec:
  weight: 9
  consolidation:
    enabled: true
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"] 
    - key: "kubernetes.io/os"
      operator: In
      values: ["linux"] 
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["2"]    
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  limits:
    resources:
      cpu: 1000
  taints:
    - key: "dedicated"
      value: "opt-karp-on-demand-cons"
      effect: "NoSchedule"
  labels:
    node-type: "opt-karp-on-demand-cons"
  providerRef:
    name: default
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    alpha.eksctl.io/cluster-name: "partner-sandbox-3"
  securityGroupSelector:
    aws:eks:cluster-name: "partner-sandbox-3"
